"""Create economic_observations table

Revision ID: 37bf24b44188
Revises: 
Create Date: 2026-02-20 18:29:01.967585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bf24b44188'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'date', name='uq_series_date')
    )
    op.create_index('idx_series_date', 'economic_observations', ['series_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_series_date', table_name='economic_observations')
    op.drop_table('economic_observations')
    # ### end Alembic commands ###
